Ep/scoped for
SpiderLabs/ModSecurity pull request #3090
Opened 2024-02-21 12:57 UTC by devzero2000

Patches in this series reduce the scope of variables in a for loop. In general, it is a commonly considered useful refactoring

2024-02-21 19:32 UTC, dune73 commented
Thank you for your contribution @devzero2000. It's been a while. Good to see you are still working on ModSec.

2024-02-21 21:04 UTC, airween requested changes

2024-02-21 21:04 UTC, airween commented on src/parser/seclang-scanner.cc
The file `seclang-scanner.cc` is a generated file by `flex` - see the [note](https://github.com/owasp-modsecurity/ModSecurity/blob/1146f4593e5e7695ea7e3af3a71e95f30649cabb/src/parser/seclang-scanner.cc#L6) in the header of the file. Every modifications will be lost after a new build process (eg. if you pass the `--enable-parser-generation` option to `./configure`. Please remove that from the PR.

2024-02-24 10:26 UTC, devzero2000 commented on src/parser/seclang-scanner.cc
deleted the seclang-scanner.cc change from this PR

2024-02-24 12:34 UTC, airween commented on src/parser/seclang-scanner.cc
As I see you completely removed the file from the repository.

I asked you only remove it from the PR (from the pull request), not from the repository. `seclang-scanner.cc` is a part of the source tree.

You should have only revert the commit [c121ec5](https://github.com/owasp-modsecurity/ModSecurity/pull/3090/commits/c121ec5314e5d6bc84d116029f139854fdbcb1f5).

2024-02-29 18:50 UTC, closed without merging

2024-02-29 18:51 UTC, devzero2000 commented
I'll do the pr again

2024-02-29 19:18 UTC, airween commented
> I'll do the pr again

Thanks!