Enhanced logging [Issue #3107]
SpiderLabs/ModSecurity pull request #3139
Opened 2024-05-10 15:31 UTC by marcstern

In case too many keys, indicate this in the audit log

2024-05-15 20:02 UTC, airween requested changes

2024-05-15 20:02 UTC, airween commented on apache2/msc_json.c
> +        if (msr->json->yajl_error) *error_msg = msr->json->yajl_error;
Could you set the correct indentation for this block? Just for the better readability.

2024-05-15 20:24 UTC, airween commented
I see that you added a new "extra" line:
```
ModSecurity: JSON parsing error: More than 10 JSON keys [hostname "localhost"] [uri "/post"] [unique_id "ZkUWkhdCjBcNkeH57qvdrgAAAAA"]
ModSecurity: Warning. Match of "eq 0" against "REQBODY_ERROR" required. [file "/etc/modsecurity/modsecurity.conf"] [line "77"] [id "20
0002"] [msg "Failed to parse request body."] [data "JSON parsing error: More than 10 JSON keys"] [severity "CRITICAL"] [hostname "localhost"] [uri "/post"] [unique_id "ZkUWkhdCjBcNkeH57qvdrgAAAAA"]
```

The first line contains the cause and the second the triggered rule details (with the cause too).

It's good for me, just asking: do we need the first line? (it does not contain extra information)

Cc @kkrupka - is this what you would like to have?

2024-05-16 07:13 UTC, kkrupka commented
Perfect. Thanks!

2024-05-16 14:13 UTC, marcstern commented
I didn't add any line, it's automatically added.
Should be the case before the change (except that it would be the generic message about the "callback").

2024-05-16 19:01 UTC, airween approved these changes

2024-05-16 19:02 UTC, airween commented
> I didn't add any line, it's automatically added. Should be the case before the change (except that it would be the generic message about the "callback").

Ok, thanks.

I'm going to merge it now - thank you. Then it closes #3107.

2024-05-16 19:02 UTC, merged