msc_regexec() != PCRE_ERROR_NOMATCH
SpiderLabs/ModSecurity pull request #3194
Opened 2024-07-22 15:09 UTC by marcstern

Return of msc_regexec() compared with PCRE_ERROR_NOMATCH (!=) to check if match.
Other errors may happen that would return -2, -3, ...
Matching would be incorrectly set in this case.
We must check if >= 0

2024-07-31 16:19 UTC, airween requested changes

2024-07-31 16:19 UTC, airween commented on apache2/re_variables.c
> +                if (msc_regexec((msc_regex_t *)var->param_data, arg->name, arg->name_len, &my_error_msg) >= 0) match = 1;
There is another problem with the old implementation: `PCRE_ERROR_NOMATCH` is a macro of the old PCRE (PCRE3) library, but the function `msc_regex()` calls another inside function which can use the old (PCRE3) and the new (PCRE2) functions - these functions use their own macros.

I just took a quick review at PCRE(2|3) macros, I really hope that each macro with value >= 0 means that's a successfully execution.

And one more question here: if `msc_regex()` called with 4th argument (`&my_error_msg`), and there is something error (retval < 0), then there will be a string allocation and the error will be stored in this variable, right? Where will this pointer freed?

What do you think?

2024-08-12 14:32 UTC, marcstern commented on apache2/re_variables.c
> +                if (msc_regexec((msc_regex_t *)var->param_data, arg->name, arg->name_len, &my_error_msg) >= 0) match = 1;
You're right, `my_error_msg` won't be deallocated, but that's not important ... because it's not allocated.
That parameter is never used.
We'll have to fix that later: either remove the parameter or add the error message.

2024-08-12 14:39 UTC, airween commented on apache2/re_variables.c
> +                if (msc_regexec((msc_regex_t *)var->param_data, arg->name, arg->name_len, &my_error_msg) >= 0) match = 1;
Ah, now I see - `my_error_msg` address is passed, **checked(!)**, but never used... I didn't checked the code after [this] line, so I thought it's a necessary variable - but now I see it completely makes no sense.

Thanks.

2024-08-12 14:40 UTC, airween approved these changes

2024-08-12 14:40 UTC, merged