Add PR's to CHANGES
SpiderLabs/ModSecurity pull request #3206
Opened 2024-08-03 14:25 UTC by airween

## what

Add PR's to `CHANGES`

## why

PR's weren't added during the merge process.

2024-08-03 14:25 UTC, airween commented
Do not approve nor merge this yet.

2024-09-02 20:23 UTC, airween commented
I think it's done, I do not want to add anything else. I removed [do not merge] label.

2024-09-03 05:40 UTC, theseion requested changes

2024-09-03 05:40 UTC, theseion commented on CHANGES
> +  - Creating a std::string with a null pointer\
```suggestion
  - Creating a std::string with a null pointer
```

2024-09-03 05:57 UTC, theseion approved these changes

2024-09-03 13:20 UTC, merged