Don't explicitly use files for mutex creation
SpiderLabs/ModSecurity pull request #3285
Opened 2024-10-22 14:23 UTC by marcstern

We don't have to generate a temp name ourselves, it'll be done in apr_global_mutex_create().
We don't have to provide a filename, apr_global_mutex_create() generates one automatically.
Moreover, under Unix & Windows, the preferred mechanism won't use a file at all.
apr_file_mktemp() cannot be used as it creates the file (at least on FreeBSD).
Discussion in Apache mailing list: https://lists.apache.org/thread/ykb26kg4lgcqnldvxwd9p6hv16fy4z9l

2024-10-31 16:02 UTC, airween requested changes

2024-10-31 16:02 UTC, airween commented on apache2/modsecurity.h
> +int msr_global_mutex_unlock(modsec_rec* msr, apr_global_mutex_t* lock, const char* fct);
Why are these declarations here? I can't find any implementation in any other places.

2024-11-12 16:30 UTC, airween commented
@marcstern ping.

2024-11-12 16:42 UTC, marcstern commented on apache2/modsecurity.h
> +int msr_global_mutex_unlock(modsec_rec* msr, apr_global_mutex_t* lock, const char* fct);
Indeed, it's fixed

2024-11-22 12:09 UTC, fzipi approved these changes
There is no better feeling than removing unneeded code.

2025-05-09 13:53 UTC, notroj approved these changes

2025-05-09 13:53 UTC, notroj commented on apache2/modsecurity.c
>          ap_log_perror(APLOG_MARK, APLOG_ERR, 0, mp, " ModSecurity: Could not create global mutex");
Passing `rc` as the `apr_status_t` argument rather than `0` as the  argument here would be better.

2025-05-16 07:57 UTC, airween commented
@notroj,

could you help us to review this PR and finish it (if it's necessary to do anything). Thanks!

2025-05-16 09:15 UTC, notroj commented
I can't push to this PR branch but I'd add:

https://github.com/notroj/ModSecurity/commit/aac61ae4263521bae01e222599241d7874b65d58

and merge this

2025-05-16 09:22 UTC, airween commented
> I can't push to this PR branch but I'd add:
> 
> [notroj@aac61ae](https://github.com/notroj/ModSecurity/commit/aac61ae4263521bae01e222599241d7874b65d58)
> 
> and merge this

Ah, you're right - thanks. Probably we should open a new PR, based on this one and then odd yours.

I can do that later or feel free to do it.

Thanks anyway.

2025-05-16 09:39 UTC, notroj commented
Actually it looks like the first commits from this PR were merged already in 1121ef0bed4f083eb6de1e7c49daf49ab554a1da and the third one looks wrong. So I just made a new PR #3385 with the suggested change. I think this PR can be closed.

2025-05-17 12:50 UTC, airween commented
Seems like this PR is orphan, I mean the modifications are the part of an another PR (#3269) and already merged. Closing as the issue is solved and PR is abandoned.

2025-05-17 12:50 UTC, closed without merging